"use client";

import { useMemo, useState } from "react";

type Service = { id: string; name: string; icon: string; description: string; question: string };
type Department = { id: string; name: string; urdu: string; icon: string; description: string; services: Service[] };
type SourceInfo = { department?: string; title?: string; url?: string; lastVerified?: string; liveVerified?: boolean; checkedAt?: string; province?: string };
type ApiResponse = { answer?: string; source?: SourceInfo | null; error?: string };

const departments: Department[] = [
  { id: "nadra", name: "NADRA Services", urdu: "نادرا کی خدمات", icon: "🪪", description: "CNIC, family certificates and identity services", services: [
    { id: "cnic", name: "CNIC / Smart CNIC", icon: "🪪", description: "New CNIC and general information", question: "How can I apply for a new CNIC?" }, { id: "cnic-renewal", name: "CNIC Renewal", icon: "🔄", description: "Renew an existing CNIC", question: "How can I renew my CNIC?" }, { id: "cnic-modification", name: "CNIC Modification", icon: "✏️", description: "Correct or update CNIC information", question: "How can I modify my CNIC information?" }, { id: "cnic-reprint", name: "CNIC Reprint / Lost", icon: "♻️", description: "Lost or damaged CNIC", question: "How can I get a reprint of my lost CNIC?" }, { id: "crc", name: "CRC / B-Form", icon: "👶", description: "Child Registration Certificate", question: "How can I apply for a CRC / B-Form?" }, { id: "juvenile", name: "Juvenile Card", icon: "🧒", description: "Identity document for children", question: "How can I apply for a Juvenile Card?" }, { id: "frc", name: "Family Registration Certificate", icon: "👨‍👩‍👧‍👦", description: "Family composition certificate", question: "How can I obtain an FRC?" }, { id: "nicop", name: "NICOP", icon: "🌍", description: "For overseas Pakistanis", question: "How can I apply for NICOP?" }, { id: "poc", name: "POC", icon: "🌐", description: "Pakistan Origin Card", question: "How can I apply for a POC?" }, { id: "cancellation", name: "Cancellation Certificate", icon: "📄", description: "NADRA cancellation services", question: "How can I apply for a Cancellation Certificate?" }, { id: "pakid", name: "PakID Services", icon: "📱", description: "NADRA online services", question: "What services are available through PakID?" }, { id: "fees", name: "NADRA Fees & Processing", icon: "💰", description: "Current fees and timelines", question: "What are the current NADRA fees and processing times?" },
  ]},
  { id: "passport", name: "Passport & Immigration", urdu: "پاسپورٹ اور امیگریشن", icon: "🛂", description: "Passport and immigration information", services: [
    { id: "passport", name: "Passport", icon: "🛂", description: "New passport", question: "How can I apply for a passport?" }, { id: "renewal", name: "Passport Renewal", icon: "🔄", description: "Renew a passport", question: "How can I renew my passport?" }, { id: "modification", name: "Passport Modification", icon: "✏️", description: "Modify passport information", question: "How can I modify my passport information?" }, { id: "lost", name: "Lost Passport", icon: "⚠️", description: "Lost passport procedure", question: "What should I do if my passport is lost?" }, { id: "immigration", name: "Immigration Information", icon: "🌍", description: "General immigration information", question: "What immigration procedures are available?" },
  ]},
  { id: "union-council", name: "Union Council / Local Government", urdu: "یونین کونسل / بلدیاتی خدمات", icon: "🏛️", description: "Civil registration and local services", services: [
    { id: "birth", name: "Birth Certificate", icon: "👶", description: "Birth registration", question: "How can I obtain a birth certificate?" }, { id: "death", name: "Death Certificate", icon: "📜", description: "Death registration", question: "How can I obtain a death certificate?" }, { id: "marriage", name: "Marriage Certificate", icon: "💍", description: "Marriage registration", question: "How can I obtain a marriage certificate?" }, { id: "divorce", name: "Divorce Certificate", icon: "📄", description: "Divorce registration", question: "How can I obtain a divorce certificate?" }, { id: "civil", name: "Civil Registration", icon: "📝", description: "Local civil registration", question: "What civil registration services are available?" },
  ]},
  { id: "domicile", name: "Domicile", urdu: "ڈومیسائل", icon: "📍", description: "Domicile and permanent residence", services: [
    { id: "new", name: "New Domicile", icon: "📍", description: "Apply for domicile", question: "How can I apply for a domicile certificate?" }, { id: "documents", name: "Required Documents", icon: "📄", description: "Domicile documents", question: "What documents are required for domicile?" }, { id: "fee", name: "Domicile Fee", icon: "💰", description: "Fees and charges", question: "What is the domicile fee?" }, { id: "verification", name: "Domicile Verification", icon: "🔎", description: "Verify domicile", question: "How can I verify a domicile certificate?" }, { id: "status", name: "Application Status", icon: "📊", description: "Check application status", question: "How can I check my domicile application status?" },
  ]},
  { id: "driving-licence", name: "Driving Licence", urdu: "ڈرائیونگ لائسنس", icon: "🚗", description: "Driving licence, learner permit, renewal and testing", services: [
    { id: "learner", name: "Learner Licence", icon: "📝", description: "Apply for a learner licence", question: "How can I apply for a learner driving licence?" }, { id: "permanent", name: "Permanent Driving Licence", icon: "🚗", description: "Apply for a permanent driving licence", question: "How can I apply for a permanent driving licence?" }, { id: "renewal", name: "Licence Renewal", icon: "🔄", description: "Renew a driving licence", question: "How can I renew my driving licence?" }, { id: "duplicate", name: "Duplicate / Lost Licence", icon: "♻️", description: "Replace a lost or damaged licence", question: "How can I get a duplicate driving licence if my licence is lost?" }, { id: "documents", name: "Required Documents", icon: "📄", description: "Documents for driving licence services", question: "What documents are required for a driving licence?" }, { id: "fee", name: "Driving Licence Fee", icon: "💰", description: "Current licence fees", question: "What is the current driving licence fee?" }, { id: "test", name: "Driving Test", icon: "🛣️", description: "Driving test information", question: "What is the driving test procedure for a driving licence?" }, { id: "online", name: "Online Application", icon: "💻", description: "Online driving licence services", question: "How can I apply for driving licence services online?" }, { id: "status", name: "Application / Licence Status", icon: "📊", description: "Check licence application or status", question: "How can I check my driving licence application status?" },
  ]},
  { id: "arms-licence", name: "Arms Licence", urdu: "اسلحہ لائسنس", icon: "🔐", description: "Arms licence application, renewal and government procedures", services: [
    { id: "application", name: "Arms Licence Application", icon: "📝", description: "Arms licence application information", question: "How can I apply for an arms licence?" }, { id: "renewal", name: "Arms Licence Renewal", icon: "🔄", description: "Arms licence renewal information", question: "How can I renew an arms licence?" }, { id: "documents", name: "Required Documents", icon: "📄", description: "Documents required for an arms licence", question: "What documents are required for an arms licence?" }, { id: "procedure", name: "Procedure", icon: "📋", description: "Arms licence application procedure", question: "What is the procedure for obtaining an arms licence?" },
  ]},
  { id: "protector", name: "Protector & Overseas Employment", urdu: "پروٹیکٹر اور بیرون ملک ملازمت", icon: "✈️", description: "Overseas employment services", services: [
    { id: "protector", name: "Protector of Emigrants", icon: "🛡️", description: "Protector registration", question: "How can I obtain Protector of Emigrants registration?" }, { id: "overseas", name: "Overseas Employment", icon: "✈️", description: "Employment abroad", question: "What is the process for going abroad for employment?" }, { id: "fees", name: "Protector Fees", icon: "💰", description: "Current fees", question: "What are the current Protector fees?" }, { id: "promoters", name: "Licensed Employment Promoters", icon: "🏢", description: "Verify licensed promoters", question: "How can I verify a licensed employment promoter?" },
  ]},
  { id: "vaccination", name: "Vaccination for Travelling Abroad", urdu: "بیرونِ ملک سفر کے لیے ویکسینیشن", icon: "💉", description: "Travel vaccination, polio and yellow fever information", services: [
    { id: "travel-vaccination", name: "Travel Vaccination", icon: "💉", description: "Vaccination requirements for international travel", question: "What vaccinations are required for travelling abroad from Pakistan?" }, { id: "polio", name: "Polio Vaccination", icon: "🧪", description: "Polio vaccination and certificate information", question: "How can I get a polio vaccination certificate for international travel?" }, { id: "yellow-fever", name: "Yellow Fever", icon: "🧪", description: "Yellow fever vaccination and certificate information", question: "How can I get a yellow fever vaccination certificate for international travel?" }, { id: "hajj-umrah", name: "Hajj & Umrah", icon: "🕋", description: "Vaccination information for Hajj and Umrah travel", question: "What vaccinations are required for Hajj or Umrah from Pakistan?" },
  ]},
  { id: "land", name: "Land & Revenue", urdu: "اراضی اور ریونیو", icon: "🏠", description: "Land records and revenue", services: [
    { id: "fard", name: "Fard / Land Record", icon: "📜", description: "Land ownership record", question: "How can I obtain a Fard or land record?" }, { id: "mutation", name: "Mutation / Intiqal", icon: "🔄", description: "Land mutation", question: "How can I apply for land mutation or Intiqal?" }, { id: "land-verification", name: "Land Record Verification", icon: "🔎", description: "Verify land records", question: "How can I verify a land record?" },
  ]},
  { id: "fbr", name: "FBR / Taxation", urdu: "ایف بی آر / ٹیکس", icon: "💰", description: "Federal tax services", services: [
    { id: "ntn", name: "Income Tax / NTN", icon: "🧾", description: "Tax registration", question: "How can I register for income tax and obtain an NTN?" }, { id: "return", name: "Income Tax Return", icon: "📑", description: "Tax return filing", question: "How can I file my income tax return?" }, { id: "taxpayer", name: "Taxpayer Verification", icon: "🔎", description: "Verify taxpayer status", question: "How can I verify my taxpayer status?" }, { id: "atl", name: "Active Taxpayer List", icon: "📋", description: "ATL / filer status", question: "How can I check my Active Taxpayer List status?" }, { id: "iris", name: "FBR IRIS", icon: "💻", description: "FBR online portal", question: "What services are available through FBR IRIS?" },
  ]},
  { id: "education", name: "Education & Scholarships", urdu: "تعلیم اور وظائف", icon: "🎓", description: "Scholarships and education", services: [
    { id: "hec", name: "HEC Scholarships", icon: "🎓", description: "HEC scholarship information", question: "What HEC scholarships are available?" }, { id: "eligibility", name: "Scholarship Eligibility", icon: "✅", description: "Eligibility criteria", question: "How can I check scholarship eligibility?" }, { id: "application", name: "Scholarship Application", icon: "📝", description: "How to apply", question: "How can I apply for a government scholarship?" }, { id: "directory", name: "Scholarship Directory", icon: "📚", description: "Official opportunities", question: "Where can I find official scholarship opportunities?" },
  ]},
  { id: "jobs", name: "Government Jobs", urdu: "سرکاری ملازمتیں", icon: "💼", description: "Official government recruitment", services: [
    { id: "federal", name: "Federal Government Jobs", icon: "🇵🇰", description: "Federal vacancies", question: "Where can I find official federal government jobs?" }, { id: "provincial", name: "Provincial Government Jobs", icon: "🏛️", description: "Provincial vacancies", question: "Where can I find official provincial government jobs?" }, { id: "application", name: "How to Apply", icon: "📝", description: "Application guidance", question: "How can I apply for a government job?" },
  ]},
  { id: "police", name: "Police Services", urdu: "پولیس کی خدمات", icon: "👮", description: "Verification and police facilitation", services: [
    { id: "clearance", name: "Police Clearance Certificate", icon: "📜", description: "Police clearance", question: "How can I obtain a Police Clearance Certificate?" }, { id: "character", name: "Police Character Certificate", icon: "📄", description: "Character certificate", question: "How can I obtain a Police Character Certificate?" }, { id: "verification", name: "Police Verification", icon: "🔎", description: "Police verification", question: "How can I apply for police verification?" }, { id: "tenant", name: "Tenant Verification", icon: "🏠", description: "Tenant verification", question: "How can I get tenant verification?" }, { id: "employee", name: "Employee Verification", icon: "👤", description: "Employee verification", question: "How can I apply for employee verification?" }, { id: "fir", name: "FIR / Police Complaint", icon: "🚨", description: "Complaint and FIR information", question: "How can I register a police complaint or FIR?" },
  ]},
  { id: "excise", name: "Excise & Taxation", urdu: "ایکسائز اینڈ ٹیکسیشن", icon: "🚗", description: "Vehicle registration and taxation", services: [
    { id: "registration", name: "Motor Vehicle Registration", icon: "🚗", description: "Register a vehicle", question: "How can I register a motor vehicle?" }, { id: "transfer", name: "Vehicle Ownership Transfer", icon: "🔁", description: "Transfer ownership", question: "How can I transfer vehicle ownership?" }, { id: "token", name: "Vehicle Token Tax", icon: "💰", description: "Vehicle tax payment", question: "How can I pay vehicle token tax?" }, { id: "verification", name: "Vehicle Verification", icon: "🔎", description: "Verify vehicle information", question: "How can I verify a vehicle?" }, { id: "renewal", name: "Vehicle Registration Renewal", icon: "🔄", description: "Renew registration", question: "How can I renew vehicle registration?" }, { id: "plate", name: "Number Plate", icon: "🔢", description: "Number plate information", question: "How can I obtain or replace a number plate?" },
  ]},
];

export default function Home() {
  const [language, setLanguage] = useState<"English" | "Urdu">("English");
  const [department, setDepartment] = useState<Department | null>(null);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<ApiResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState("");
  const [copied, setCopied] = useState(false);

  const isUrdu = language === "Urdu";
  const visibleDepartments = useMemo(() => { const q = search.trim().toLowerCase(); return q ? departments.filter(d => `${d.name} ${d.urdu} ${d.description}`.toLowerCase().includes(q)) : departments; }, [search]);
  const suggestions = useMemo(() => department ? (department.id === "nadra" ? ["What are the current CNIC and Smart CNIC fees?", "What documents are required for CNIC?", "What are the CRC photo and biometric requirements by age?", "How can I apply through PakID?"] : ["What services and requirements are available?", "What documents are required?", "What is the fee?", "How can I apply?"]) : [], [department]);
  const goHome = () => { setDepartment(null); setAnswer(null); setQuestion(""); setSearch(""); setCopied(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const goDepartment = () => { setAnswer(null); setQuestion(""); };
  const ask = async () => {
    if (!question.trim() || !department) return;
    setLoading(true); setAnswer(null); setCopied(false);
    try {
      const res = await fetch("/api/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: question.trim(), service: department.name, language, department: department.name }) });
      const data = await res.json();
      setAnswer(data);
    } catch { setAnswer({ error: "Unable to connect to the verified information service. Please try again." }); }
    finally { setLoading(false); }
  };

  const copyAnswer = async () => { if (!answer?.answer) return; try { await navigator.clipboard.writeText(answer.answer); setCopied(true); window.setTimeout(() => setCopied(false), 1600); } catch {} };

  return (
    <main className="app-shell" dir={isUrdu ? "rtl" : "ltr"}>
      <header className="topbar">
        <div className="topbar-inner">
          <button className="brand" onClick={goHome} aria-label="Home">
            <span className="brand-mark">🇵🇰</span>
            <span><strong>Pakistan Citizen Helper</strong><small>{isUrdu ? "مصدقہ سرکاری معلومات" : "Verified Government Information Portal"}</small></span>
          </button>
          <div className="top-actions"><span className="secure-pill">✓ {isUrdu ? "مصدقہ معلومات" : "Verified"}</span><button className={`lang ${!isUrdu ? "active" : ""}`} onClick={() => setLanguage("English")}>English</button><button className={`lang ${isUrdu ? "active" : ""}`} onClick={() => setLanguage("Urdu")}>اردو</button></div>
        </div>
      </header>

      <section className="content">
        {!department && <>
          <section className="hero">
            <div className="hero-copy"><span className="hero-kicker">🇵🇰 {isUrdu ? "پاکستانی شہریوں کے لیے" : "FOR CITIZENS OF PAKISTAN"}</span><h1>{isUrdu ? "سرکاری خدمات، آسان اور قابلِ اعتماد" : "Government services, made simple and trustworthy."}</h1><p>{isUrdu ? "مصدقہ سرکاری معلومات تلاش کریں، سوال پوچھیں اور متعلقہ سرکاری ذریعہ براہِ راست دیکھیں۔" : "Find verified government information, ask a question, and access the relevant official source."}</p><div className="hero-trust"><span>✓ {isUrdu ? "سرکاری ذرائع" : "Official sources"}</span><span>✓ {isUrdu ? "مصدقہ معلومات" : "Verified information"}</span><span>✓ {isUrdu ? "مفت رسائی" : "Free access"}</span></div></div>
            <div className="hero-seal"><span>🇵🇰</span><small>PAKISTAN<br/>CITIZEN<br/>HELPER</small></div>
          </section>
          <section className="welcome"><div><span className="eyebrow">{isUrdu ? "خوش آمدید" : "WELCOME"}</span><h2>{isUrdu ? "آپ کو کس سرکاری سروس کی معلومات چاہیے؟" : "What government service do you need?"}</h2><p>{isUrdu ? "شروع کرنے کے لیے ایک محکمہ منتخب کریں۔" : "Select a department below to get started."}</p></div><div className="trust-badge"><span>✓</span><small>{isUrdu ? "مصدقہ" : "Verified"}<br/>{isUrdu ? "معلومات" : "Information"}</small></div></section>
          <section className="trust-strip"><div><strong>01</strong><span>{isUrdu ? "محکمہ منتخب کریں" : "Choose a department"}</span></div><div><strong>02</strong><span>{isUrdu ? "سوال پوچھیں" : "Ask your question"}</span></div><div><strong>03</strong><span>{isUrdu ? "مصدقہ جواب حاصل کریں" : "Get verified guidance"}</span></div></section>
          <div className="section-head"><div><span className="eyebrow">{isUrdu ? "خدمات" : "SERVICES"}</span><h2>{isUrdu ? "سرکاری محکمے" : "Government departments"}</h2><p>{isUrdu ? "اپنی مطلوبہ سروس تلاش کرنے کے لیے محکمہ منتخب کریں" : "Choose a department to find the service you need."}</p></div><span className="count">{visibleDepartments.length}<small>/ {departments.length}</small></span></div>
          <div className="department-search"><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder={isUrdu ? "محکمے تلاش کریں..." : "Search departments..."} aria-label="Search departments" />{search && <button onClick={() => setSearch("")} aria-label="Clear search">×</button>}</div>
          <div className="department-grid">{visibleDepartments.map((d, i) => <button key={d.id} className={`department-card ${i === 0 ? "featured" : ""}`} onClick={() => setDepartment(d)}><span className="card-number">{String(i + 1).padStart(2, "0")}</span><span className="card-icon">{d.icon}</span><span className="card-text"><strong>{isUrdu ? d.urdu : d.name}</strong><small>{d.description}</small></span><span className="arrow">→</span></button>)}</div>
        </>}

        {department && <section className="view question-view"><button className="back" onClick={goHome}>← {isUrdu ? "تمام محکمے" : "All departments"}</button><div className="service-banner"><span className="service-banner-icon">{department.icon}</span><div><div className="eyebrow">{isUrdu ? "محکمہ" : "DEPARTMENT"}</div><h1>{isUrdu ? department.urdu : department.name}</h1><p>{isUrdu ? "اس محکمے سے متعلق کوئی بھی سوال پوچھیں" : "Ask any question related to this government department."}</p></div></div>
          {!answer && <><div className="question-card"><div className="question-heading"><span className="question-mark">?</span><div><label>{isUrdu ? "اپنا سوال لکھیں" : "What would you like to know?"}</label><small>{isUrdu ? "آپ اس محکمے کی کسی بھی سروس کے بارے میں سوال پوچھ سکتے ہیں۔" : "Ask anything about this department. You do not need to select a specific service."}</small></div></div><textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder={isUrdu ? `مثلاً: ${department?.name} سے متعلق کوئی سوال پوچھیں` : `For example: What is the fee? What documents are required?`} rows={5} /><button className="primary" onClick={ask} disabled={loading || !question.trim()}><span>{loading ? "Checking verified information…" : isUrdu ? "مصدقہ جواب حاصل کریں" : "Get verified answer"}</span><span>→</span></button></div><div className="suggestions"><span>{isUrdu ? "عام سوالات" : "COMMON QUESTIONS"}</span>{suggestions.map((q,i) => <button key={i} onClick={() => setQuestion(q)}>{q}</button>)}</div></>}
          {answer && <div className="answer-area"><div className={`answer-card ${answer.error ? "is-warning" : ""}`}>{answer.error ? <><div className="status-icon warning">!</div><div className="verified-label">{isUrdu ? "معلومات دستیاب نہیں" : "INFORMATION UNAVAILABLE"}</div><h2>{isUrdu ? "مصدقہ معلومات نہیں مل سکیں" : "Verified information is unavailable"}</h2><p>{answer.error}</p></> : <><div className="answer-top"><div className="status-icon">✓</div><div><div className="verified-label">{isUrdu ? "مصدقہ سرکاری معلومات" : "VERIFIED GOVERNMENT INFORMATION"}</div><small>{isUrdu ? "دستیاب سرکاری معلومات کی بنیاد پر" : "Based on available official information"}</small></div></div><div className="answer-text">{answer.answer}</div><button className="copy-button" onClick={copyAnswer}>{copied ? "✓ Copied" : "⧉ Copy answer"}</button></>}</div>{answer.source && <div className="source-card"><div className="source-main"><span className="source-icon">↗</span><div><span className="source-label">{isUrdu ? "سرکاری ذریعہ" : "OFFICIAL SOURCE"}</span><strong>{answer.source.title || "Official government source"}</strong><small>{answer.source.department || department.name}{answer.source.lastVerified ? ` · Verified ${answer.source.lastVerified}` : ""}</small></div></div>{answer.source.url && <a href={answer.source.url} target="_blank" rel="noreferrer">{isUrdu ? "سرکاری ویب سائٹ کھولیں" : "Visit official source"} ↗</a>}</div>}<button className="secondary" onClick={() => { setAnswer(null); setQuestion(""); }}>↻ {isUrdu ? "دوسرا سوال پوچھیں" : "Ask another question"}</button></div>}
        </section>}

      </section>
      <footer><div><strong>Pakistan Citizen Helper</strong><span>•</span><span>{isUrdu ? "مصدقہ سرکاری معلومات" : "Verified Government Information"}</span></div><div className="footer-note">{isUrdu ? "حساس ذاتی معلومات، CNIC نمبر، پاس ورڈ یا OTP درج نہ کریں۔" : "Do not enter sensitive personal information, CNIC numbers, passwords or OTPs."}</div><p>Developed by <strong>Raees Khan</strong> · Assistant Director, NADRA</p></footer>
    </main>
  );
}
